### ISSUE TITLE
Add Rust skin definitions

### ISSUE THREAD

**Issue by Tommeh1** [umod/docs#1]
As uMod is now behind Cloudflare it's impossible to get certain data automatically off of the website.
So i'm hoping it's possible to add the contents of https://umod.org/documentation/games/rust/definitions#skins to this repo.

**Comment by lukespragg** [comment]
Are you attempting to scrape the site for that data? If so, there are more efficient means, even via server-side plugin. The documentation here is currently just a development area.

**Comment by Tommeh1** [comment]
Last i checked, which was a while ago you had to get the payed version of such plugin to get that data.
Hence why i scraped it.

**Comment by lukespragg** [comment]
While I've not tested this recently, here's an example via a plugin:
[Exporter.zip](https://github.com/umod/docs/files/9077391/Exporter.zip)

**Comment by Tommeh1** [comment]
Thx, id test it but i currently don't have a server setup to test it on, i'm working on a serious set of Python code to automate every bit of my server possible first.
I'll close the issue for now and get back to it down the line if it happens to run into issues.
